### PR TITLE
Fix encoding for `fetch_bbs_data()` and `stratify()`

### LINKED ISSUE #192: fetch_bbs_data not working (again)
After the recent fix for the `fetch_bbs_data` function, I'm getting this error:

```{r}
Type "yes" (without quotes) to agree: yes
Using data directory at C:\Users\adam_\AppData\Local/bbsBayes/bbsBayes
Connecting to USGS ScienceBase...Connected!
Downloading count data (Task 1/3)
[===================================================================================] 100% eta:  0s
Downloading route data (Task 2/3)
[===================================================================================] 100% eta:  0s
Downloading species data (Task 3/3)
[====================>--------------------------------------------------------------]  25% eta:  1sError in substring(x, first, last) : 
  invalid multibyte string at '<e0> ve'
```

This is with the most recent development version and the CRAN version. 

```{r}
R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22000)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                           LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bbsBayes_2.5.1

loaded via a namespace (and not attached):
 [1] httr_1.4.3          rnaturalearth_0.1.0 pkgload_1.3.0       jsonlite_1.8.0      splines_4.2.0       geofacet_0.2.0     
 [7] shiny_1.7.1         assertthat_0.2.1    sp_1.5-0            progress_1.2.2      remotes_2.4.2       ggrepel_0.9.1      
[13] sessioninfo_1.2.2   pillar_1.8.0        lattice_0.20-45     glue_1.6.2          digest_0.6.29       promises_1.2.0.1   
[19] colorspace_2.0-3    Matrix_1.4-1        htmltools_0.5.2     httpuv_1.6.5        pkgconfig_2.0.3     devtools_2.4.4     
[25] purrr_0.3.4         xtable_1.8-4        scales_1.2.0        processx_3.5.3      rjags_4-13          jpeg_0.1-9         
[31] later_1.3.0         tibble_3.1.7        proxy_0.4-27        mgcv_1.8-40         generics_0.1.3      ggplot2_3.3.6      
[37] usethis_2.1.6       ellipsis_0.3.2      cachem_1.0.6        withr_2.5.0         cli_3.3.0           magrittr_2.0.3     
[43] crayon_1.5.1        mime_0.12           memoise_2.0.1       ps_1.7.0            fs_1.5.2            fansi_1.0.3        
[49] nlme_3.1-157        jagsUI_1.5.2        class_7.3-20        pkgbuild_1.3.1      profvis_0.3.7       tools_4.2.0        
[55] imguR_1.0.3         prettyunits_1.1.1   hms_1.1.1           lifecycle_1.0.1     stringr_1.4.0       munsell_0.5.0      
[61] geogrid_0.1.1       sbtools_1.1.19      callr_3.7.0         compiler_4.2.0      e1071_1.7-11        rlang_1.0.4        
[67] classInt_0.4-7      units_0.8-0         grid_4.2.0          rstudioapi_0.13     rappdirs_0.3.3      htmlwidgets_1.5.4  
[73] miniUI_0.1.1.1      gtable_0.3.0        DBI_1.1.3           curl_4.3.2          R6_2.5.1            gridExtra_2.3      
[79] dplyr_1.0.9         fastmap_1.1.0       rgeos_0.5-9         utf8_1.2.2          rprojroot_2.0.3     KernSmooth_2.23-20 
[85] stringi_1.7.6       parallel_4.2.0      Rcpp_1.0.8.3        vctrs_0.4.1         sf_1.0-8            png_0.1-7          
[91] coda_0.19-4         tidyselect_1.1.2    urlchecker_1.0.1   
```

### PR DESCRIPTION
**Pull request by steffilazerte**
This should fix #192 by providing explicit file encodings of latin1. 

1. Install this PR by going into your `bbsBayes` project and fetching this PR
```
usethis::pr_fetch(197)
```

2. Use `devtools::load_all(".")` to load the current version of the package (also Ctrl-Shift-L)

3. To test, try the following
```
fetch_bbs_data("state", force = TRUE)  # Should have no errors

b <- load_bbs_data()
head(b$species)     # Should have proper accents in French names

s <- stratify(by = "bbs_usgs")
s$species_strat[634:638,]  # Should have proper accents, including in 'lumped' species
```

4. Once you're done, get rid of the PR with
```
usethis::pr_finish()
```

Let me know how it goes!

### CODE REVIEW

**Comment by AdamCSmithCWS** [comment]
Thank you! 

I can confirm that this works on my Windows system.

**Comment by BrandonEdwards** [comment]
I get the following error message when running fetch_bbs_data() after following the instructions:
```
Error in read.table(file = FILE, header = header, sep = sep, row.names = row.names,  : 
  no lines available in input
In addition: Warning messages:
1: In readLines(file, n = skip) :
  invalid input found on input connection 'C:\Users\brand\AppData\Local\Temp\RtmpKW44zA\file2834337eeba'
2: In readLines(file, n = skip) :

Error in read.table(file = FILE, header = header, sep = sep, row.names = row.names, : 
no lines available in input
4.
stop("no lines available in input")
3.
read.table(file = FILE, header = header, sep = sep, row.names = row.names, 
col.names = col.names, quote = "", ...)
2.
utils::read.fwf(temp, skip = lskip, strip.white = TRUE, header = FALSE, 
colClasses = c("integer", "character", "character", "character", 
"character", "character", "character", "character", "character"), 
widths = c(6, -1, 5, -1, 50, -1, 50, -1, 50, -1, 50, -1, ... at fetch-bbs-data.R#206
1.
fetch_bbs_data("state", force = TRUE)
```

Which is what I believe was the same error message I was getting and Tim was getting in #191. Here is my sessionInfo (I know, I know, I need to update R):

> R version 4.0.3 (2020-10-10)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 19043)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252    LC_MONETARY=English_Canada.1252
> [4] LC_NUMERIC=C                    LC_TIME=English_Canada.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] bbsBayes_2.5.2.9000
> 
> loaded via a namespace (and not attached):
>  [1] httr_1.4.2          rnaturalearth_0.1.0 pkgload_1.1.0       jsonlite_1.7.3     
>  [5] splines_4.0.3       geofacet_0.2.0      assertthat_0.2.1    sp_1.4-4           
>  [9] blob_1.2.1          remotes_2.4.1       progress_1.2.2      ggrepel_0.8.2      
> [13] sessioninfo_1.1.1   pillar_1.6.4        lattice_0.20-41     glue_1.6.2         
> [17] digest_0.6.29       colorspace_2.0-2    Matrix_1.2-18       pkgconfig_2.0.3    
> [21] devtools_2.3.2      purrr_0.3.4         scales_1.1.1        processx_3.7.0     
> [25] rjags_4-10          jpeg_0.1-8.1        git2r_0.27.1        tibble_3.1.6       
> [29] mgcv_1.8-33         generics_0.1.1      ggplot2_3.3.5       usethis_1.6.3      
> [33] ellipsis_0.3.2      withr_2.5.0         cli_3.4.1           magrittr_2.0.1     
> [37] crayon_1.4.2        memoise_1.1.0       ps_1.4.0            fs_1.5.0           
> [41] fansi_1.0.2         nlme_3.1-150        jagsUI_1.5.1        class_7.3-17       
> [45] pkgbuild_1.1.0      tools_4.0.3         gh_1.1.0            imguR_1.0.3        
> [49] prettyunits_1.1.1   hms_0.5.3           lifecycle_1.0.1     stringr_1.4.0      
> [53] munsell_0.5.0       geogrid_0.1.1       sbtools_1.1.12      callr_3.5.1        
> [57] compiler_4.0.3      e1071_1.7-4         rlang_0.4.12        classInt_0.4-3     
> [61] units_0.6-7         grid_4.0.3          rstudioapi_0.11     rappdirs_0.3.1     
> [65] testthat_3.0.0      gtable_0.3.0        DBI_1.1.0           curl_4.3           
> [69] R6_2.5.1            gridExtra_2.3       dplyr_1.0.7         rgeos_0.5-5        
> [73] utf8_1.2.2          rprojroot_2.0.2     KernSmooth_2.23-18  desc_1.2.0         
> [77] stringi_1.7.6       parallel_4.0.3      Rcpp_1.0.7          vctrs_0.3.8        
> [81] sf_1.0-3            png_0.1-7           tidyselect_1.1.1    coda_0.19-4

**Comment by steffilazerte** [comment]
Hmm, that's a new error, not the encoding problem from earlier, and also not the error fro #191. 

Can I suggest a complete purge of your files?

-  `unlink(list.files(tempdir(), full.names = TRUE), recursive = TRUE)`
- `unlink(rappdirs::app_dir(appname = "bbsBayes")$data(), recursive = TRUE)`

Then try again from scratch.

If that doesn't work and you get the same error, try opening the file (e.g., above it was `C:\Users\brand\AppData\Local\Temp\RtmpKW44zA\file2834337eeba`) in a local text editor and see if there's anything indicative!

**Comment by BrandonEdwards** [comment]
I get the following error:
```
Creating data directory at C:\Users\brand\AppData\Local\bbsBayes\bbsBayes
Connecting to USGS ScienceBase...Connected!
Downloading count data (Task 1/3)
[===================================================================================] 100% eta:  0s
Downloading route data (Task 2/3)
[===================================================================================] 100% eta:  0s
Downloading species data (Task 3/3)
[====================>--------------------------------------------------------------]  25% eta:  2sError in read.table(file = FILE, header = header, sep = sep, row.names = row.names,  : 
  no lines available in input
In addition: Warning messages:
1: In readLines(file, n = skip) :
  invalid input found on input connection 'C:\Users\brand\AppData\Local\Temp\RtmpCu9oJM\file4c282921423e'
2: In readLines(file, n = skip) :
 
 Error in read.table(file = FILE, header = header, sep = sep, row.names = row.names, : 
no lines available in input
4.
stop("no lines available in input")
3.
read.table(file = FILE, header = header, sep = sep, row.names = row.names, 
col.names = col.names, quote = "", ...)
2.
utils::read.fwf(temp, skip = lskip, strip.white = TRUE, header = FALSE, 
colClasses = c("integer", "character", "character", "character", 
"character", "character", "character", "character", "character"), 
widths = c(6, -1, 5, -1, 50, -1, 50, -1, 50, -1, 50, -1, ... at fetch-bbs-data.R#206
1.
fetch_bbs_data("state", force = TRUE)
```
Which is the same error I received above. However, I do not get this error on the master branch, where there is no encoding. 

So, looking at some differences in sessionInfo() between myself, @tmeeha from #191, and @AdamCSmithCWS from #192 , the only real differences I'm seeing is what is under the "locale" list. For ease, I will copy each here:

Mine:

> <environment: namespace:bbsBayes>
> > sessionInfo()
> R version 4.0.3 (2020-10-10)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 19043)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252    LC_MONETARY=English_Canada.1252
> [4] LC_NUMERIC=C                    LC_TIME=English_Canada.1252 

@tmeeha:

> session info:
> R version 4.1.1 (2021-08-10)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 19044)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United States.1252 LC_CTYPE=English_United States.1252 LC_MONETARY=English_United States.1252 LC_NUMERIC=C
> [5] LC_TIME=English_United States.1252

@AdamCSmithCWS :

> R version 4.2.0 (2022-04-22 ucrt)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 22000)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8
> [4] LC_NUMERIC=C                           LC_TIME=English_United States.utf8

Note that both @tmeeha and I have the same stuff under "locale", and bbsBayes worked for us from my "fix" here: https://github.com/BrandonEdwards/bbsBayes/commit/728da1eea84f975984534e74b862de1f30799c73, which then messed it up on Adam's system.

I'm afraid off hand that I do not know what those different locales imply, but I'd be curious to see @steffilazerte what your sessionInfo() looks like, particularly in the locale section. I wonder if there is going to have to be some sort of "locale-specific encoding" that we use, where some locales need to specify an encoding, and some don't? Certainly an odd one...

**Comment by steffilazerte** [comment]
Hmmmmmmmmmm,
```
R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.1 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C               LC_TIME=en_CA.UTF-8        LC_COLLATE=en_CA.UTF-8    
 [5] LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8    LC_PAPER=en_CA.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C 
```

I think the relevant thing here is the `.utf8` that Adam and I have vs. the `.1252` that you and Tim have. Argh. I think this is also related to the R version 4.2 as according to the docs, Windows changed things in that version.

SO! I've modified the branch to include a `get_encoding()` function, which looks at your locale and if you're a UTF-8 local (like me and Adam) fixes the encoding, but leaves it alone if you're not (like Brandon and Tim?)

Anyway  @AdamCSmithCWS and @BrandonEdwards could you both try again and see if a) it still works for Adam and b) it now works for Brandon?

Thanks!

**Comment by BrandonEdwards** [comment]
Success!! 

I assume that since both you and Adam experienced the same issues during the same time, that it _should_ work for him too. I think he's out of the office for a few days, so I'll wait until he's confirmed before I go ahead and merge this.

Thanks @steffilazerte , you rock!!

**Comment by AdamCSmithCWS** [comment]
> Success!!
> 
> I assume that since both you and Adam experienced the same issues during the same time, that it _should_ work for him too. I think he's out of the office for a few days, so I'll wait until he's confirmed before I go ahead and merge this.
> 
> Thanks @steffilazerte , you rock!!

Works for me, too!

**Pull request merged**
